baseURL = "/"
languageCode = "en-us"
title = "Froggodoggo"
theme = "kosmos"

[params]
  description = "Froggodoggo helps companies hire awesome founders who are looking for a side gig." 

[permalinks]
  blog = "/blog/:slug"